### ISSUE TITLE
使用org-capture时，在capture buffer中会在headline前面加空格

### ISSUE THREAD

**Issue by moonwwdz** [manateelazycat/wraplish#9]
## 问题
使用org-capture时，在capture buffer中会在headline前面加空格，这样会造成格式不统一，如下图中的**两个红框**中标记
![image](https://github.com/manateelazycat/wraplish/assets/6963514/d8e0774e-d0d2-4928-bf52-296ef95de2b5)

## 环境
- Armbian OS 24.5.0 Bookworm with Linux 5.15.148-ophub
- GNU Emacs 28.2

## 配置
为还原这个问题使用的最简化的配置，所有配置都在init.el文件中
```emacs-lisp

(global-set-key (kbd "C-c c") 'org-capture)
;;工作日志

(require 'org-capture)                      
(add-to-list 'org-capture-templates
             '("w" "Work Journal" entry (file+datetree "~/.emacs.d/t.org")
               "* %U - %^{heading}\n  %?"))

;; 英文空格
(add-to-list 'load-path "~/.emacs.d/wraplish")
(require 'wraplish)
(dolist (hook (list 'markdown-mode-hook 'org-mode-hook))
  (add-hook hook #'(lambda () (wraplish-mode 1))))
(setq wraplish-enable-debug t)
(setq wraplish-enable-log t)
```
## *wraplish*
```text
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ff68bf1a0 (LWP 31587)]
[New Thread 0x7ff5f201a0 (LWP 31588)]
[New Thread 0x7ff55811a0 (LWP 31589)]
[New Thread 0x7ff4be21a0 (LWP 31590)]
[New Thread 0x7fe7fff1a0 (LWP 31591)]
[New Thread 0x7fe76601a0 (LWP 31592)]
[New Thread 0x7fe6cc11a0 (LWP 31593)]
[Thread 0x7fe6cc11a0 (LWP 31593) exited]
[New Thread 0x7fe6cc11a0 (LWP 31620)]
[New Thread 0x7fe63221a0 (LWP 31621)]
[New Thread 0x7fe59831a0 (LWP 31622)]
[Thread 0x7fe6cc11a0 (LWP 31620) exited]
[New Thread 0x7fe6cc11a0 (LWP 31623)]
[New Thread 0x7fe4fe41a0 (LWP 31624)]
[Thread 0x7fe59831a0 (LWP 31622) exited]
[Thread 0x7fe4fe41a0 (LWP 31624) exited]
[New Thread 0x7fe4fe41a0 (LWP 31625)]
[New Thread 0x7fe59831a0 (LWP 31626)]
[Thread 0x7fe4fe41a0 (LWP 31625) exited]
[New Thread 0x7fe4fe41a0 (LWP 31627)]
[New Thread 0x7fcbfff1a0 (LWP 31628)]
[Thread 0x7fe4fe41a0 (LWP 31627) exited]
[New Thread 0x7fe4fe41a0 (LWP 31629)]
[Thread 0x7fcbfff1a0 (LWP 31628) exited]
[New Thread 0x7fcb6601a0 (LWP 31630)]
[New Thread 0x7fcbfff1a0 (LWP 31631)]
[Thread 0x7fcb6601a0 (LWP 31630) exited]
[New Thread 0x7fcb6601a0 (LWP 31632)]
[Thread 0x7fe6cc11a0 (LWP 31623) exited]
[Thread 0x7fe63221a0 (LWP 31621) exited]
[New Thread 0x7fe6cc11a0 (LWP 31633)]
[Thread 0x7fe6cc11a0 (LWP 31633) exited]
[Thread 0x7fe59831a0 (LWP 31626) exited]
[New Thread 0x7fe59831a0 (LWP 31634)]
Exception in thread Thread-8 (find_space_positions):
[Thread 0x7fe59831a0 (LWP 31634) exited]
Exception in thread Thread-9 (find_space_positions):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "/root/.emacs.d/wraplish/wraplish.py", line 163, in find_space_positions
    for match in re.finditer(r'([a-zA-Z])([\u4e00-\u9fff])', text):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 223, in finditer
    return _compile(pattern, flags).finditer(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'list'
[Thread 0x7fcbfff1a0 (LWP 31631) exited]
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/root/.emacs.d/wraplish/wraplish.py", line 163, in find_space_positions
    for match in re.finditer(r'([a-zA-Z])([\u4e00-\u9fff])', text):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 223, in finditer
    return _compile(pattern, flags).finditer(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'list'
[Thread 0x7fe4fe41a0 (LWP 31629) exited]
[New Thread 0x7fe4fe41a0 (LWP 31635)]
[Thread 0x7fe4fe41a0 (LWP 31635) exited]
[Thread 0x7fcb6601a0 (LWP 31632) exited]
[New Thread 0x7fcb6601a0 (LWP 31636)]
[New Thread 0x7fe4fe41a0 (LWP 31637)]
[Thread 0x7fe4fe41a0 (LWP 31637) exited]
[New Thread 0x7fe4fe41a0 (LWP 31638)]
[Thread 0x7fcb6601a0 (LWP 31636) exited]
[Thread 0x7fe4fe41a0 (LWP 31638) exited]
```

**Comment by manateelazycat** [comment]
wraplish 应该不适合 org-mode， 因为 org-mode 的语法格式太复杂， 会有太多org插件和语法.

wraplish 更适合 txt 和 markdown 格式。
